"""Initial Migration

Revision ID: 775bf94d1549
Revises: 
Create Date: 2024-01-15 20:32:24.555047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775bf94d1549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('departmentnumber', sa.Integer(), nullable=False),
    sa.Column('departmentName', sa.String(), nullable=False),
    sa.Column('departmentHead', sa.String(), nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('departmentnumber'),
    sa.UniqueConstraint('departmentnumber')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('midint', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('departmentnumber', sa.String(length=20), nullable=False),
    sa.Column('hiredate', sa.DateTime(), nullable=False),
    sa.Column('educationlevel', sa.String(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departmentnumber'], ['department.departmentnumber'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('department')
    # ### end Alembic commands ###
