"""Initial Migration

Revision ID: 778ce896500d
Revises: 
Create Date: 2024-02-22 11:19:12.432906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778ce896500d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('departmentnumber', sa.Integer(), nullable=False),
    sa.Column('departmentName', sa.String(), nullable=False),
    sa.Column('departmentHead', sa.String(), nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('departmentnumber')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('dateOfBirth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('IdentificationNumber', sa.Integer(), nullable=False),
    sa.Column('departmentnumber', sa.Integer(), nullable=False),
    sa.Column('dateOfEmployment', sa.DateTime(), nullable=False),
    sa.Column('contractPeriod', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['departmentnumber'], ['assignment.departmentnumber'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IdentificationNumber'),
    sa.UniqueConstraint('contact'),
    sa.UniqueConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('passport_filepath', sa.String(), nullable=False),
    sa.Column('IdCopy_filepath', sa.String(), nullable=False),
    sa.Column('ChiefLetter_filepath', sa.String(), nullable=False),
    sa.Column('ClearanceLetter_filepath', sa.String(), nullable=False),
    sa.Column('Reference_filepath', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('employee')
    op.drop_table('assignment')
    # ### end Alembic commands ###
